# Generated by Django 3.1.5 on 2021-01-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0002_auto_20210127_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toptic',
            new_name='Topic',
        ),
    ]
